ABILITIES = {
    'LVL1_ABILITIES': {
        'Strike': {
            'description': 'A basic attack that deals damage to a single target.',
            'effect_1': 'DAM_PHYS_ATK_1_ENEMY',
            'value_1': '0.8',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
        'Punch': {
            'description': 'A basic attack that deals damage to a single target.',
            'effect_1': 'DAM_PHYS_ATK_1_ENEMY',
            'value_1': '0.8 * PHYS_ATK',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
        'Kick': {
            'description': 'A basic attack that deals damage to a single target.',
            'effect_1': 'DAM_PHYS_ATK_1_ENEMY',
            'value_1': '0.8 * PHYS_ATK',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
        'Shoot': {
            'description': 'A basic attack that deals damage to a single target.',
            'effect_1': 'DAM_PIR_ATK_1_ENEMY',
            'value_1': '0.8 * PIR_ATK',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
        'Fireball': {
            'description': 'A basic attack that deals damage to a single target.',
            'effect_1': 'DAM_MAG_ATK_1_ENEMY',
            'value_1': '0.8 * MAG_ATK',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
        'Lesser Heal': {
            'description': 'Restore HP to a single target.',
            'effect_1': 'HEAL_1_ALLY',
            'value_1': '1.2 * MAG_ATK',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
        'Lesser Debaser': {
            'description': 'Reduce all target\'s DEFs.',
            'effect_1': 'DEBUFF_DEF_ALL_1_ENEMY',
            'value_1': '5',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
        'Lesser Enhance': {
            'description': 'Increase all your\'s ATKs.',
            'effect_1': 'BUFF_ATK_ALL_SELF',
            'value_1': ' 3',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
        'Lesser Fortify': {
            'description': 'Increase all your\'s DEFs.',
            'effect_1': 'BUFF_DEF_ALL_SELF',
            'value_1': '4',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
        'Anger': {
            'description': 'Increase your PHYS ATK',
            'effect_1': 'BUFF_ATK_PHYS_SELF',
            'value_1': '6',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
        'Focus': {
            'description': 'Increase your PIR ATK',
            'effect_1': 'BUFF_ATK_PIR_SELF',
            'value_1': '6',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
        'Concentration': {
            'description': 'Increase your MAG ATK',
            'effect_1': 'BUFF_ATK_MAG_SELF',
            'value_1': '6',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        }
    },
    'LVL3_ABILITIES': {
        # Add a test ability
        'Test Ability': {
            'description': 'A test ability that does nothing.',
            'effect_1': 'NONE',
            'value_1': '0',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
        'Test #2': {
            'description': 'A test ability that does nothing.',
            'effect_1': 'NONE',
            'value_1': '0',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
    },
    
    'LVL5_ABILITIES': {
        # Add a test ability
        'Test Ability': {
            'description': 'A test ability that does nothing.',
            'effect_1': 'NONE',
            'value_1': '0',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
       
    },
    'LVL8_ABILITIES': {
        # Add a test ability
        'Test Ability': {
            'description': 'A test ability that does nothing.',
            'effect_1': 'NONE',
            'value_1': '0',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
       
        },
    'LVL10_ABILITIES': {
        # Add a test ability
        'Test Ability': {
            'description': 'A test ability that does nothing.',
            'effect_1': 'NONE',
            'value_1': '0',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
           
        },
    'LVL13_ABILITIES': {
         # Add a test ability
        'Test Ability': {
            'description': 'A test ability that does nothing.',
            'effect_1': 'NONE',
            'value_1': '0',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
          
        },
    'LVL15_ABILITIES': {
          # Add a test ability
        'Test Ability': {
            'description': 'A test ability that does nothing.',
            'effect_1': 'NONE',
            'value_1': '0',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
         
        },
    'LVL18_ABILITIES': {
          # Add a test ability
        'Test Ability': {
            'description': 'A test ability that does nothing.',
            'effect_1': 'NONE',
            'value_1': '0',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
         
        },
    'LVL20_ABILITIES': {
            # Add a test ability
        'Test Ability': {
            'description': 'A test ability that does nothing.',
            'effect_1': 'NONE',
            'value_1': '0',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
       
        },
    'LVL23_ABILITIES': {
            # Add a test ability
        'Test Ability': {
            'description': 'A test ability that does nothing.',
            'effect_1': 'NONE',
            'value_1': '0',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
       
        },
    'LVL25_ABILITIES': {
           # Add a test ability
        'Test Ability': {
            'description': 'A test ability that does nothing.',
            'effect_1': 'NONE',
            'value_1': '0',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
        
        },
    'LVL28_ABILITIES': {
            # Add a test ability
        'Test Ability': {
            'description': 'A test ability that does nothing.',
            'effect_1': 'NONE',
            'value_1': '0',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
       
        },
    'LVL30_ABILITIES': {
            # Add a test ability
        'Test Ability': {
            'description': 'A test ability that does nothing.',
            'effect_1': 'NONE',
            'value_1': '0',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
       
        },
    'LVL33_ABILITIES': {
            # Add a test ability
        'Test Ability': {
            'description': 'A test ability that does nothing.',
            'effect_1': 'NONE',
            'value_1': '0',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
       
        },
    'LVL35_ABILITIES': {
            # Add a test ability
        'Test Ability': {
            'description': 'A test ability that does nothing.',
            'effect_1': 'NONE',
            'value_1': '0',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
       
        },
    'LVL38_ABILITIES': {
            # Add a test ability
        'Test Ability': {
            'description': 'A test ability that does nothing.',
            'effect_1': 'NONE',
            'value_1': '0',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
        'Overpowered Ability #2': {
            'description': 'A test ability that does everything.',
            'effect_1': 'DAM_PHYS_ATK_1_ENEMY',
            'value_1': '0.8 * PHYS_ATK',
            'effect_2': 'DAM_PIR_ATK_1_ENEMY',
            'value_2': '0.8 * PIR_ATK',
            'effect_3': 'DAM_MAG_ATK_1_ENEMY',
            'value_3': '0.8 * MAG_ATK',
            'effect_4': 'HEAL_1_ALLY',
            'value_4': '1.2 * MAG_ATK',
            'effect_5': 'DEBUFF_DEF_ALL_1_ENEMY',
            'value_5': '5',
            'effect_6': 'BUFF_ATK_ALL_SELF',
            'value_6': '3',
            'cooldown': '0',
        },
       
        },
    'LVL40_ABILITIES': {
            # Add a test ability
        'Test Ability': {
            'description': 'A test ability that does nothing.',
            'effect_1': 'NONE',
            'value_1': '0',
            'effect_2': 'NONE',
            'value_2': '0',
            'effect_3': 'NONE',
            'value_3': '0',
            'effect_4': 'NONE',
            'value_4': '0',
            'effect_5': 'NONE',
            'value_5': '0',
            'effect_6': 'NONE',
            'value_6': '0',
            'cooldown': '0',
        },
        'Overpowered Ability #2': {
            'description': 'A test ability that does everything.',
            'effect_1': 'DAM_PHYS_ATK_1_ENEMY',
            'value_1': '0.8 * PHYS_ATK',
            'effect_2': 'DAM_PIR_ATK_1_ENEMY',
            'value_2': '0.8 * PIR_ATK',
            'effect_3': 'DAM_MAG_ATK_1_ENEMY',
            'value_3': '0.8 * MAG_ATK',
            'effect_4': 'HEAL_1_ALLY',
            'value_4': '1.2 * MAG_ATK',
            'effect_5': 'DEBUFF_DEF_ALL_1_ENEMY',
            'value_5': '5',
            'effect_6': 'BUFF_ATK_ALL_SELF',
            'value_6': '3',
            'cooldown': '0',
        },
       
    }
}
